displayName=Gielinor Cartography

author=jacke9708
description=Play Turf Wars in Gielinor with highscores.
tags=turf,territory,pvm,skilling,leaderboard,minigame,multiplayer
version=1.0.0
plugins=com.gielinorcartography.GielinorCartographyPlugin
build=standard